# Generated by Django 5.2.7 on 2025-10-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicsnote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs/'),
        ),
    ]
