# Generated by Django 5.2.7 on 2025-10-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='details',
            field=models.JSONField(help_text='Stores question-wise answers and timings'),
        ),
    ]
