# Generated by Django 5.2.7 on 2025-10-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_simulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='page_url',
        ),
        migrations.AddField(
            model_name='simulation',
            name='content_html',
            field=models.TextField(blank=True, help_text='Optional custom HTML/JS simulation code'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
